FROM debian:stretch-slim

EXPOSE 8080 \
       8443

ENV HTTPD_VERSION=2.4 \
    HTTPD_RELEASE=2.4.29 \
    HTTPD_CHECKSUM=777753a5a25568a2a27428b2214980564bc1c38c1abf9ccc7630b639991f7f00 \
    HTTPD_SOURCE=/usr/src/httpd \
    HTTPD_TARBALL=/usr/src/httpd-2.4.29.tar.bz2 \
    HOME=/srv/www

LABEL name="tomashavlas/httpd" \
      version="${HTTPD_VERSION}" \
      release="${HTTPD_RELEASE}" \
      maintaner="Tomáš Havlas <tomas@havlas.me>" \
      vendor="Tomáš Havlas" \
      io.openshift.s2i.scripts-url=image:///usr/lib/s2i

ENV HTTPD_CONF_PATH=/etc/httpd \
    HTTPD_CONFD_PATH=/etc/httpd/conf.d \
    HTTPD_DEFAULTD_PATH=/etc/httpd/default.d \
    HTTPD_LOCK_PATH=/var/lock/httpd \
    HTTPD_LOG_PATH=/var/log/httpd \
    HTTPD_MODULESD_PATH=/etc/httpd/modules.d \
    HTTPD_RUN_PATH=/run/httpd

RUN useradd --home-dir /usr/share/httpd --gid 0 --shell /usr/sbin/nologin --system --uid 48 apache \
    \
 && apt-get update \
 && BUILD_DEPS=" \
        gcc \
        libapr1-dev \
        libaprutil1-dev \
        libpcre++-dev \
        libssl1.0-dev \
        make \
        zlib1g-dev " \
 && RUNTIME_DEPS=" \
        bzip2 \
        gettext-base \
        libapr1 \
        libaprutil1 \
        libnss-wrapper \
        libpcre++0v5 \
        libssl1.0.2 \
        zlib1g " \
 && apt-get install --yes --no-install-recommends --verbose-versions ${BUILD_DEPS} ${RUNTIME_DEPS} \
 \
 && rm --recursive /var/lib/apt/lists/*

RUN apt-get update \
 && BUILD_DEPS=" \
        ca-certificates \
        wget " \
 && apt-get install --yes --no-install-recommends --verbose-versions ${BUILD_DEPS} \
 \
 && wget -O "${HTTPD_TARBALL}" "https://www.apache.org/dyn/closer.cgi?action=download&filename=httpd/httpd-${HTTPD_RELEASE}.tar.bz2" \
 && echo "${HTTPD_CHECKSUM} *${HTTPD_TARBALL}" | sha256sum --check - \
 \
 && apt-get purge --yes --auto-remove ${BUILD_DEPS} \
 && rm --recursive /var/lib/apt/lists/*

COPY [ "./root/usr/bin/docker-httpd-*", "/usr/bin/" ]

RUN docker-httpd-source extract \
 && docker-httpd-install \
        --enable-mods-shared=all \
        --enable-mpms-shared=all \
        --enable-so \
 && docker-httpd-source delete

ENV CONTAINER_ENTRYPOINT_PATH=/usr/share/container-entrypoint \
    CONTAINER_PASSWD_PATH="${HTTPD_CONF_PATH}/passwd" \
    S2I_BIN_PATH=/usr/lib/s2i

COPY [ "./s2i/bin", "${S2I_BIN_PATH}/" ]
COPY [ "./common/root", "./root", "./${HTTPD_VERSION}/root", "/" ]
RUN /usr/lib/container-entrypoint/httpd-setup \
 && /usr/lib/container-entrypoint/httpd-generate-modulesd \
 && docker-httpd-module enable \
        auth_basic \
        authn_core \
        authn_file \
        authz_core \
        authz_host \
        authz_user \
        mime \
        mpm_prefork \
        unixd \
 && test "$( id apache )" = "uid=48(apache) gid=0(root) groups=0(root)"

USER 48

WORKDIR "${HOME}"
ENTRYPOINT [ "container-entrypoint" ]
CMD [ "/usr/lib/s2i/usage" ]
