FROM debian:stretch-slim

EXPOSE 8080 \
       8443

ENV HTTPD_VERSION=2.4 \
    HTTPD_RELEASE=2.4.29 \
    HTTPD_CHECKSUM=948e4a11278a5954698b880b30f401b1e9ab743713ee2c7280a54dd4ddd87085 \
    HTTPD_SOURCE=/usr/src/httpd \
    HTTPD_TARBALL=/usr/src/httpd-2.4.29.tar.gz \
    HOME=/srv/www

LABEL name="tomashavlas/httpd" \
      version="${HTTPD_VERSION}" \
      release="1" \
      maintaner="Tomáš Havlas <tomas@havlas.me>" \
      vendor="Tomáš Havlas" \
      io.openshift.s2i.scripts-url=image:///usr/lib/s2i

ENV HTTPD_CONF_PATH=/etc/httpd \
    HTTPD_CONFD_PATH=/etc/httpd/conf.d \
    HTTPD_DEFAULTD_PATH=/etc/httpd/default.d \
    HTTPD_LOCK_PATH=/var/lock/httpd \
    HTTPD_LOG_PATH=/var/log/httpd \
    HTTPD_MODULESD_PATH=/etc/httpd/modules.d \
    HTTPD_RUN_PATH=/run/httpd

RUN useradd --home-dir /usr/share/httpd --gid 0 --shell /usr/sbin/nologin --system --uid 48 apache \
    \
 && apt-get update \
 && RUNTIME_DEPS=" \
        gettext-base \
        libnss-wrapper \
        libapr1 \
        libaprutil1 \
        libpcre++0v5 \
        libssl1.0.2 \
        zlib1g " \
 && apt-get install --yes --no-install-recommends --verbose-versions ${RUNTIME_DEPS} \
 && rm --recursive /var/lib/apt/lists/*

RUN apt-get update \
 && BUILD_DEPS=" \
        ca-certificates \
        gcc \
        libapr1-dev \
        libaprutil1-dev \
        libpcre++-dev \
        libssl1.0-dev \
        make \
        wget \
        zlib1g-dev " \
 && apt-get install --yes --no-install-recommends --verbose-versions ${BUILD_DEPS} \
 \
 && wget -O "${HTTPD_TARBALL}" "https://www.apache.org/dyn/closer.cgi?action=download&filename=httpd/httpd-${HTTPD_RELEASE}.tar.gz" \
 && echo "${HTTPD_CHECKSUM} *${HTTPD_TARBALL}" | sha256sum --check - \
 \
 && mkdir -p "${HTTPD_SOURCE}" \
 && tar --extract --gzip --strip-components=1 \
        --directory="${HTTPD_SOURCE}" \
        --file="${HTTPD_TARBALL}" \
 \
 && cd "${HTTPD_SOURCE}" \
 && { \
        echo; \
        echo '# Container'; \
        echo '<Layout Container>'; \
        echo '    prefix:           '; \
        echo '    exec_prefix:      /usr'; \
        echo '    bindir:           ${exec_prefix}/bin'; \
        echo '    cgidir:           ${datadir}/cgi-bin'; \
        echo '    datadir:          ${exec_prefix}/share/httpd'; \
        echo '    errordir:         ${datadir}/error'; \
        echo '    htdocsdir:        ${datadir}/htdocs'; \
        echo '    iconsdir:         ${datadir}/icons'; \
        echo '    includedir:       ${exec_prefix}/include/httpd'; \
        echo '    infodir:          ${exec_prefix}/share/info'; \
        echo '    installbuilddir:  ${libdir}/httpd/build'; \
        echo '    libdir:           ${exec_prefix}/lib'; \
        echo '    libexecdir:       ${libdir}/httpd/modules'; \
        echo "    localstatedir:    \${prefix}${HTTPD_LOCK_PATH}"; \
        echo "    logfiledir:       \${prefix}${HTTPD_LOG_PATH}"; \
        echo '    mandir:           ${exec_prefix}/share/man'; \
        echo '    manualdir:        ${datadir}/manual'; \
        echo '    proxycachedir:    ${prefix}/var/cache/httpd/proxy'; \
        echo "    runtimedir:       \${prefix}${HTTPD_RUN_PATH}"; \
        echo '    sbindir:          ${exec_prefix}/sbin'; \
        echo "    sysconfdir:       \${prefix}${HTTPD_CONF_PATH}"; \
        echo '</Layout>'; \
 } >> config.layout \
 && ./configure \
        --enable-layout=Container \
        --enable-mods-shared=realyall \
        --enable-mpms-shared=all \
 && make --jobs=$( nproc ) \
 && make --jobs=$( nproc ) install \
 && install --directory --group=0 --mode=0770 --owner=48 \
        "${HOME}" \
        "${HTTPD_CONFD_PATH}" \
        "${HTTPD_DEFAULTD_PATH}" \
        "${HTTPD_LOCK_PATH}" \
        "${HTTPD_LOG_PATH}" \
        "${HTTPD_MODULESD_PATH}" \
        "${HTTPD_RUN_PATH}" \
 && cd / \
 && rm --recursive \
        "${HTTPD_CONF_PATH}/original" \
        "${HTTPD_SOURCE}" \
        "${HTTPD_TARBALL}" \
        /usr/lib/httpd/build \
        /usr/share/httpd/manual \
        /usr/share/man/* \
 \
 && apt-get purge --yes --auto-remove ${BUILD_DEPS} \
 && rm --recursive /var/lib/apt/lists/* \
 \
 && test "$( id apache )" = "uid=48(apache) gid=0(root) groups=0(root)"

ENV CONTAINER_ENTRYPOINT_PATH=/usr/share/container-entrypoint \
    CONTAINER_PASSWD_PATH="${HTTPD_CONF_PATH}/passwd" \
    S2I_BIN_PATH=/usr/lib/s2i

COPY [ "./s2i/bin", "${S2I_BIN_PATH}/" ]
COPY [ "./common/root", "./root", "./${HTTPD_VERSION}/root", "/" ]
RUN /usr/lib/container-entrypoint/httpd-setup \
 && /usr/lib/container-entrypoint/httpd-generate-modulesd \
 && docker-httpd-module-enable \
        auth_basic \
        authn_core \
        authn_file \
        authz_core \
        authz_host \
        authz_user \
        mime \
        mpm_prefork \
        unixd

USER 48

WORKDIR "${HOME}"
ENTRYPOINT [ "container-entrypoint" ]
CMD [ "/usr/lib/s2i/usage" ]
